version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "
      npm rebuild bcrypt --build-from-source &&
      npx prisma migrate dev --name init &&
      node server.js
      "
    restart: always

networks:
  app-network:
    driver: bridge
